# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pascal.ui'
#
# Created: Mon Dec 08 14:29:55 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(227, 240)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 200, 151, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 5, 2, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 3, 2, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 2)
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setToolTip("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit_N_length = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_N_length.setWhatsThis("")
        self.lineEdit_N_length.setObjectName("lineEdit_N_length")
        self.gridLayout.addWidget(self.lineEdit_N_length, 0, 2, 1, 2)
        self.radioButton_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 5, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEdit_n_var = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_n_var.setObjectName("lineEdit_n_var")
        self.gridLayout.addWidget(self.lineEdit_n_var, 1, 2, 1, 2)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.lineEdit_Operation = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Operation.setObjectName("lineEdit_Operation")
        self.gridLayout.addWidget(self.lineEdit_Operation, 6, 2, 1, 2)
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 190, 201, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        #单选框进行编组
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "杨辉三角相关", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setToolTip(QtGui.QApplication.translate("Dialog", "量子", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setWhatsThis(QtGui.QApplication.translate("Dialog", "量子", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("Dialog", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setToolTip(QtGui.QApplication.translate("Dialog", "非归一化", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setWhatsThis(QtGui.QApplication.translate("Dialog", "非归一化", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Dialog", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setToolTip(QtGui.QApplication.translate("Dialog", "归一化", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setWhatsThis(QtGui.QApplication.translate("Dialog", "归一化", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Mod:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "函数范围或单个函数", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setToolTip(QtGui.QApplication.translate("Dialog", "动量", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setWhatsThis(QtGui.QApplication.translate("Dialog", "动量", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("Dialog", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Mod:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setWhatsThis(QtGui.QApplication.translate("Dialog", "函数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "f:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setWhatsThis(QtGui.QApplication.translate("Dialog", "长度", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_N_length.setPlaceholderText(QtGui.QApplication.translate("Dialog", "长度2-2000", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setToolTip(QtGui.QApplication.translate("Dialog", "经典", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setWhatsThis(QtGui.QApplication.translate("Dialog", "经典", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Mod:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "n:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_n_var.setPlaceholderText(QtGui.QApplication.translate("Dialog", "变量-默认2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setToolTip(QtGui.QApplication.translate("Dialog", "位置", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setWhatsThis(QtGui.QApplication.translate("Dialog", "位置", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "operation", None, QtGui.QApplication.UnicodeUTF8))

