# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'triangularNumber.ui'
#
# Created: Fri Mar 27 21:25:32 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TriangularNumber(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(474, 273)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 438, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_triangular = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_triangular.setObjectName("checkBox_triangular")
        self.gridLayout.addWidget(self.checkBox_triangular, 0, 1, 1, 1)
        self.checkBox_triangularNumber = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_triangularNumber.setObjectName("checkBox_triangularNumber")
        self.gridLayout.addWidget(self.checkBox_triangularNumber, 0, 3, 1, 2)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.checkBox_sortSeq = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_sortSeq.setEnabled(False)
        self.checkBox_sortSeq.setObjectName("checkBox_sortSeq")
        self.gridLayout.addWidget(self.checkBox_sortSeq, 2, 3, 1, 1)
        self.checkBox_evenSeq = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_evenSeq.setEnabled(False)
        self.checkBox_evenSeq.setObjectName("checkBox_evenSeq")
        self.gridLayout.addWidget(self.checkBox_evenSeq, 1, 4, 1, 1)
        self.checkBox_pascal = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_pascal.setEnabled(False)
        self.checkBox_pascal.setObjectName("checkBox_pascal")
        self.gridLayout.addWidget(self.checkBox_pascal, 1, 3, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 2, 1)
        self.checkBox_LongSeq = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_LongSeq.setEnabled(False)
        self.checkBox_LongSeq.setObjectName("checkBox_LongSeq")
        self.gridLayout.addWidget(self.checkBox_LongSeq, 2, 4, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.lineEdit_Number = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Number.setObjectName("lineEdit_Number")
        self.gridLayout.addWidget(self.lineEdit_Number, 6, 1, 1, 4)
        self.checkBox_HLayout = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_HLayout.setEnabled(False)
        self.checkBox_HLayout.setObjectName("checkBox_HLayout")
        self.gridLayout.addWidget(self.checkBox_HLayout, 1, 1, 1, 1)
        self.checkBox_VLayout = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_VLayout.setEnabled(False)
        self.checkBox_VLayout.setObjectName("checkBox_VLayout")
        self.gridLayout.addWidget(self.checkBox_VLayout, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(260, 240, 193, 28))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 230, 441, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "产生式三角值生成器", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_triangular.setText(QtGui.QApplication.translate("Dialog", "产生式三角", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_triangularNumber.setText(QtGui.QApplication.translate("Dialog", "产生式三角数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "内容：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "模式:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sortSeq.setToolTip(QtGui.QApplication.translate("Dialog", "Meta-Short序列", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sortSeq.setText(QtGui.QApplication.translate("Dialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_evenSeq.setToolTip(QtGui.QApplication.translate("Dialog", "偶序列", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_evenSeq.setText(QtGui.QApplication.translate("Dialog", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pascal.setToolTip(QtGui.QApplication.translate("Dialog", "杨辉三角", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pascal.setText(QtGui.QApplication.translate("Dialog", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_LongSeq.setToolTip(QtGui.QApplication.translate("Dialog", "meta - Long 序列", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_LongSeq.setText(QtGui.QApplication.translate("Dialog", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Number.setPlaceholderText(QtGui.QApplication.translate("Dialog", "N-表示最大行", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_HLayout.setText(QtGui.QApplication.translate("Dialog", "水平输出", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_VLayout.setText(QtGui.QApplication.translate("Dialog", "垂直输出", None, QtGui.QApplication.UnicodeUTF8))

