# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pascal.ui'
#
# Created: Thu Apr 02 14:10:12 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_Dialog_pascal(object):
    def setupUi(self, Dialog_pascal):
        Dialog_pascal.setObjectName("Dialog_pascal")
        Dialog_pascal.resize(288, 339)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_pascal.sizePolicy().hasHeightForWidth())
        Dialog_pascal.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtGui.QWidget(Dialog_pascal)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 314))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.radioButton_QoM = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_QoM.setObjectName("radioButton_QoM")
        self.buttonGroup = QtGui.QButtonGroup(Dialog_pascal)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_QoM)
        self.gridLayout.addWidget(self.radioButton_QoM, 4, 2, 1, 1)
        self.radioButton_position = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_position.setObjectName("radioButton_position")
        self.buttonGroup.addButton(self.radioButton_position)
        self.gridLayout.addWidget(self.radioButton_position, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 7, 1, 1, 2)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 11, 2, 1, 1)
        self.radioButton_gonssise = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_gonssise.setObjectName("radioButton_gonssise")
        self.buttonGroup_2 = QtGui.QButtonGroup(Dialog_pascal)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_gonssise)
        self.gridLayout.addWidget(self.radioButton_gonssise, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 10, 0, 1, 3)
        self.lineEdit_operation = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_operation.setObjectName("lineEdit_operation")
        self.gridLayout.addWidget(self.lineEdit_operation, 8, 1, 1, 2)
        self.radioButton_discrete = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_discrete.setObjectName("radioButton_discrete")
        self.buttonGroup_3 = QtGui.QButtonGroup(Dialog_pascal)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_discrete)
        self.gridLayout.addWidget(self.radioButton_discrete, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.radioButton_bayes = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_bayes.setObjectName("radioButton_bayes")
        self.buttonGroup_2.addButton(self.radioButton_bayes)
        self.gridLayout.addWidget(self.radioButton_bayes, 3, 2, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.radioButton_quantum = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_quantum.setObjectName("radioButton_quantum")
        self.buttonGroup_3.addButton(self.radioButton_quantum)
        self.gridLayout.addWidget(self.radioButton_quantum, 5, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_lenght = QtGui.QLabel(self.gridLayoutWidget)
        self.label_lenght.setObjectName("label_lenght")
        self.gridLayout.addWidget(self.label_lenght, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 6, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 9, 1, 1, 1)

        self.retranslateUi(Dialog_pascal)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pascal)

    def retranslateUi(self, Dialog_pascal):
        Dialog_pascal.setWindowTitle(QtGui.QApplication.translate("Dialog_pascal", "二项分布图示参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_pascal", "倍数因子：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_QoM.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "动量", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_QoM.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "动量", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_QoM.setText(QtGui.QApplication.translate("Dialog_pascal", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_position.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "位置", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_position.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "位置", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_position.setText(QtGui.QApplication.translate("Dialog_pascal", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_pascal", "操作:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog_pascal", "生成", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_gonssise.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "高斯", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_gonssise.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "高斯", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_gonssise.setText(QtGui.QApplication.translate("Dialog_pascal", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_operation.setPlaceholderText(QtGui.QApplication.translate("Dialog_pascal", "操作符", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_discrete.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "离散", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_discrete.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "经典", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_discrete.setText(QtGui.QApplication.translate("Dialog_pascal", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_pascal", "f:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog_pascal", "长度2-2000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_pascal", "Mod2:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bayes.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "贝叶斯", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bayes.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "贝叶斯", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bayes.setText(QtGui.QApplication.translate("Dialog_pascal", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setPlaceholderText(QtGui.QApplication.translate("Dialog_pascal", "变量（默认2）", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_quantum.setToolTip(QtGui.QApplication.translate("Dialog_pascal", "量子", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_quantum.setWhatsThis(QtGui.QApplication.translate("Dialog_pascal", "量子", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_quantum.setText(QtGui.QApplication.translate("Dialog_pascal", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setPlaceholderText(QtGui.QApplication.translate("Dialog_pascal", "函数范围或单个函数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_pascal", "符号：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_pascal", "n:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_pascal", "mod3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lenght.setText(QtGui.QApplication.translate("Dialog_pascal", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_pascal", "Mod1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_pascal", "排序:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setCurrentText(QtGui.QApplication.translate("Dialog_pascal", "sl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog_pascal", "sl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog_pascal", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dialog_pascal", "c", None, QtGui.QApplication.UnicodeUTF8))
